language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# only `sudo: true` allows running tests on Travis CI container infrastructure for faster builds, but testing installation of .deb makes sense
sudo: true

# Installing ghostscript (optional imagemagick dependency) is required for Html2ImageTest to run
# dpkg-dev debhelper m4 packages are required for the 'ant deb' task
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ghostscript dpkg-dev debhelper m4

install:
- cd libbuild && MAVEN_OPTS="-Xmx6g -Xms2g" mvn clean install && cd ..

script:
- MAVEN_OPTS="-Xmx6g -Xms2g" mvn clean install
# test build instructions
- ant
- ant dist
- ant deb
- sudo dpkg -i ../yacy_*_all.deb
