name: CI Script to build after pull request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: "github.repository == 'yacy/yacy_search_server'
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with ant
      run: ant clean all dist
